version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis-nodejs
    ports:
      - "6379:6379"
    networks:
      - nodejss
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME:-mysql-nodejs}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
     - "${MYSQL_PORT}:3306"  
    volumes:
    - db:/var/lib/mysql
    networks: 
      - nodejss

  web:
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    build: ./
    ports: 
     - "${APP_PORT}:3000"
    volumes:
    - ./:/app
    restart: unless-stopped
    container_name: ${APP_CONTAINER_NAME:-nodejs}
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks: 
      - nodejss

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME:-phpmyadmin}
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - nodejss

volumes:
  db:

networks:
  nodejss: